name: Trigger auto deployment for swiftfiddle-runner-functions-31

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/swiftfiddle-runner-functions-31-AutoDeployTrigger-45e35da7-23aa-4d8a-801f-86600d56f53c.yml"

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: swiftfiddle.azurecr.io
          username: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS31_REGISTRY_USERNAME }}
          password: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS31_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: swiftfiddle.azurecr.io/swiftfiddle-runner-functions-31:latest
          file: ./Dockerfile
          context: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS31_AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n swiftfiddle-runner-functions-31 -g swiftfiddle --server swiftfiddle.azurecr.io --username  ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS31_REGISTRY_USERNAME }} --password ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS31_REGISTRY_PASSWORD }}
            az containerapp update -n swiftfiddle-runner-functions-31 -g swiftfiddle --image swiftfiddle.azurecr.io/swiftfiddle-runner-functions-31:latest
