name: Trigger auto deployment for swiftfiddle-runner-functions-31

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/swiftfiddle-runner-functions-31-AutoDeployTrigger-01f0ce8b-79b7-4a70-bc51-0aec387a210f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS31_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS31_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS31_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS31_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS31_REGISTRY_PASSWORD }}
          containerAppName: swiftfiddle-runner-functions-31
          resourceGroup: swiftfiddle
          imageToBuild: kishikawakatsumi/swiftfiddle-runner-functions-31:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


